### PR TITLE
Fix alizer hanging while getting potential dockerfile locations

### PR DESCRIPTION
**Pull request by thepetk**
## What does this PR do?

This PR creates a separate slice of `string` inside the `getLocation` function, in order to avoid looping forever in the `locations` slice.

More detailed, for a big project, alizer was trying to get a all potential locations of dockerfiles with `utils.getLocations`. This process tries to locate any Dockerfile/Containerfile inside the root level or one level down. So if the `getLocations` identifies an item that is a directory inside the root dir of the component it adds this item to the list.

The above process was hanging for a big project as the `getLocations` was looping in a bigger and bigger slice. By adding the `filenames` slice and looping for potential filenames there, this issue is now fixed.

### Which issue(s) does this PR fix

fixes https://github.com/devfile/api/issues/1279

### PR acceptance criteria

Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

- [x] Unit/Functional tests

  

- [x] Documentation

### CODE REVIEW

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Review by rm3l — COMMENTED** [review]
Also, do you think it could be possible to add a test case to prevent future regressions on this?
I was thinking maybe we could enrich the `resources/projects/dockerfile-nested` test project with a bunch of new directories. And adding a timeout to the test case to make sure it does not hang. WDYT?

**Comment by thepetk** [comment]
> Also, do you think it could be possible to add a test case to prevent future regressions on this? I was thinking maybe we could enrich the `resources/projects/dockerfile-nested` test project with a bunch of new directories. And adding a timeout to the test case to make sure it does not hang. WDYT?

@rm3l I've added 20 test dirs in the test resource and updated the `getLocations` by using `copy` to create a duplicate slice.

**Review by rm3l — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
