### PR TITLE
Adding two new static file extension folders for Java Specific Workflows

### PR DESCRIPTION
**Pull request by shawn-hurley**
## What does this PR do?

When using a spring boot application in Java, many of the static files will be placed in META-INF/resources. Right now these are treated like first class concepts, eventually moving the weight of Java application down far enough to not be selected.

You can see more info about this here: https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot

### CODE REVIEW

**Review by michael-valdron — COMMENTED** [review]
Changes here looks good to me.

@thepetk I wonder if we should investigate tying project specific static file extension folders with the detection of the project source since there is many specific projects that Alizer could work with, i.e. if it detects it has Java source under the project at least, such as after running `languagesFile.GetLanguagesByExtension(extension)`, include this extra collection of static file extension folders. WDYT?

**Review by thepetk — COMMENTED** [review]
In general the addition of those 2 extra static dirs make sense to me.

Before approving I'd suggest adding an extra test case in the [language_recognizer_test.go](https://github.com/devfile/alizer/blob/main/test/apis/language_recognizer_test.go#L20) to make sure for every new feature this won't show up again.

@michael-valdron re: to your [comment](https://github.com/devfile/alizer/pull/97#pullrequestreview-2231089441). I'm supportive of creating a spike issue to investigate an improved approach for the `analyze` command.

My two cents:
* The `analyze` command tries to quickly summarize all data found for the given project. The initial approach was to count all extensions found inside a project. After the merge of  [#168](https://github.com/redhat-developer/alizer/commit/98a0064ea9a624ada22b4db1785454f325940b5f) the weight is different for static file cases.
* In order to get more info for specific modules/components that exist inside the project, one has to run `component` command. In the current `main` the `component` command is able to locate the root `java` component.
* Looking at the response format we do include information for `framework` & `tools`. This means we're already analyzing the first dir level of the given project, so we can have different weight calculation for each case, while we don't add a performance overhead to the `analyze` command.

**Comment by shawn-hurley** [comment]
Adding the test case now! thanks for the feedback!

**Comment by shawn-hurley** [comment]
@thepetk Test case for the application that I was using to see the bug was added!

**Comment by thepetk** [comment]
> @thepetk Test case for the application that I was using to see the bug was added!

@shawn-hurley would it be possible to reduce the size of the test resource we're adding? We could keep the same ratio between java/js files and ofc all config files. You could check the rest of the test resources to use as an example.

**Comment by shawn-hurley** [comment]
I think the problem was the size of the js files, does the app not have to compile or work in anyway?

**Comment by thepetk** [comment]
> I think the problem was the size of the js files, does the app not have to compile or work in anyway?

No not at all. It won't be compiled. We need only a "structure" of a project that alizer can work on. So for this case we can keep all config files, so alizer can detect the framework etc and a smaller amount of js / java files to analyze the language.

**Comment by thepetk** [comment]
> is this better?

@shawn-hurley I think much better, I'd also remove any Dockerfile, Images, License, Documentation and Kubernetes related items so the test project contains only java & js files. This way we keep alizer repo minimal while we're focusing on the specific case we've met on the test resource!

**Comment by shawn-hurley** [comment]
I think I got them all, sorry for all the extra info and stuff

**Comment by thepetk** [comment]
@shawn-hurley I've tried to remove more items (Docs, Images, Html, Css, License files). Added a commit in your branch. Feel free to revert if you think is not needed.

**Comment by shawn-hurley** [comment]
No thank you, I didn't think about looking in the components directory itself sorry!

**Review by thepetk — APPROVED** [review]
/lgtm

@shawn-hurley Nice fix! 

@michael-valdron I've created https://github.com/devfile/api/issues/1622 for the investigation we were discussing.

**Comment by thepetk** [comment]
@shawn-hurley I've also cut alizer `v1.6.1` release which includes the fix we've just merged.

**Pull request merged**
