### PR TITLE
feat: improve Quarkus component detection

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Quarkus projects often have lots of modules that are not intended to be components, but still have io.quarkus dependencies.

This commit will only mark a module as a Quarkus component if it explicitly references the Quarkus plugin that creates a runnable application.

In addition if a Java project contains components that explicitly specify frameworks then modules without frameworks will be removed.

This will help with the usability issues identified in RHTAPBUGS-552.

Testing against Apicurio Registry this reduces the component count down from 50 to 8, which is expected.

### CODE REVIEW

**Review by mike-hoang — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Is there anything else I need to do here?

**Review by thepetk — CHANGES_REQUESTED** [review]
I'm temporarily request changes, as it is still under consideration regarding the changes we make in the component detection behavior for java components.

More detailed, I want to confirm team-wise that we would like to introduce this new behavior inside the `component_recognizer.go`

**Comment by thepetk** [comment]
> I'm temporarily request changes, as it is still under consideration regarding the changes we make in the component detection behavior for java components.
> 
> More detailed, I want to confirm team-wise that we would like to introduce this new behavior inside the `component_recognizer.go`

* I think is a very nice addition to have a more tight detection logic for quarkus:
```go
//note that we don't specify the group id because this can sometimes be a property substitution
if hasFwk, _ := hasFramework(config, "", "quarkus-maven-plugin"); hasFwk {
  language.Frameworks = append(language.Frameworks, "Quarkus")
} else if hasFwk, _ = hasFramework(config, "", "io.quarkus.gradle.plugin"); hasFwk {
  language.Frameworks = append(language.Frameworks, "Quarkus")
}
```

* I see the `frameworkPreffered` as a cool feature in the future for Alizer. As right now we don't support all frameworks (or at least the most important) I think it would have big impact if we change so drastically the behavior of the detectors. Additionaly, the `framework` field is "treated" as additional information for a component atm. So after a language analysis we are trying to enrich every component found. Now, with the current workaround, we are making the framework deciding for the components.

That said, IMO I would suggest that we could keep the fix for quarkus `hasFramework` func. But I'd suggest to move [all the updates for the component filtering](https://github.com/devfile/alizer/pull/21/files#diff-1c4989a4be9d4e5c0b76fbb14a5bb86d5c77907937b592d3739f66f806897ae2R241-R257) to the consumer side and filter alizer's response there. As a result alizer will still be able to provide detailed information about the source code, avoiding the risk of skipping important components with not supported frameworks. WDYT?

**Comment by stuartwdouglas** [comment]
Sorry, I completely missed the review on this. 

The reason why I did the filtering where it is was because I wanted to consider the whole project when making this change (i.e. the hasFrameworks field). If no frameworks are detected it keeps the existing behavior.

**Comment by thepetk** [comment]
> Sorry, I completely missed the review on this.
> 
> The reason why I did the filtering where it is was because I wanted to consider the whole project when making this change (i.e. the hasFrameworks field). If no frameworks are detected it keeps the existing behavior.

@stuartwdouglas no worries!

I have went again through the proposed workaround. As mentioned in a previous comment, atm we are not covering all the frameworks so we may have cases that we are excluding a legit component. I tried to run an example for a hypothetical monolithic repo which has different components inside.

**Example dir**
```
jsf-component/
open-liberty-component/
quarkus-component/
reactjs-component/
```

From the four above components the 3 of them will be enriched with a framework (e.g. openliberty, quarkus and react). There is one which will not be enriched with a framework, the [JSF](https://www.oracle.com/java/technologies/javaserverfaces.html) (randomly picked as example).

With quarkus improvements we will be able to detect only 3 components, while with the existing functionality we are able to detect all 4 components stored in root dir.

**Comment by stuartwdouglas** [comment]
I guess to make this decision properly you would need to track dependency information between the modules. If a module with no framework is a dependency of another module with a framework, then this module is likely not a component. 

If a module is standalone then it is likely a component even without a detected framework.

That said I am not really sure how to make such a change in the current code base, I think it would be a fairly significant change.

**Comment by thepetk** [comment]
> I guess to make this decision properly you would need to track dependency information between the modules. If a module with no framework is a dependency of another module with a framework, then this module is likely not a component.
> 
> If a module is standalone then it is likely a component even without a detected framework.
> 
> That said I am not really sure how to make such a change in the current code base, I think it would be a fairly significant change.

@stuartwdouglas mostly I agree with what you are saying. The only thing I'd like to note, is that IMO a module that has no framework and is a dependency of another module could be a component. It could be detected, but we could also add a field in alizer's response mentioning any related/dependent components for each component. I see this as a cool feature for alizer. We could also add a flag like "parent-components-only" (name not important) so a user can choose if they want to see only parent components (makes this workaround backwards compatible too). WDYT?

**Pull request closed without merging**
