### PR TITLE
Add SECURITY-INSIGHTS.md

### PR DESCRIPTION
**Pull request by thepetk**
## What does this PR do?

As part of the CNCF defender tasks we need to add a `security-insights.md` to reach the 100% on the monitor. More information for the security insights here: https://github.com/ossf/security-insights-spec/blob/main/specification.md

### Which issue(s) does this PR fix

Fixes https://github.com/devfile/api/issues/1392

### PR acceptance criteria

Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

- [ ] Unit/Functional tests

  

- [ ] Documentation

### CODE REVIEW

**Review by Jdubrick — APPROVED** [review]
/lgtm

Will the threat model and vulnerability reporting be added after conclusion of the epic?

**Comment by Jdubrick** [comment]
@thepetk I was looking over the docs again and noticed there has to be a specific naming convention for the `security-insights` file to be picked up by the clomonitor scan. It has to be named `security-insights.yml`. From looking at the monitor it isn't tracking properly for alizer.

https://clomonitor.io/docs/topics/checks/#security-insights

**Comment by Jdubrick** [comment]
> @thepetk I was looking over the docs again and noticed there has to be a specific naming convention for the `security-insights` file to be picked up by the clomonitor scan. It has to be named `security-insights.yml`. From looking at the monitor it isn't tracking properly for alizer.
> 
> https://clomonitor.io/docs/topics/checks/#security-insights

never mind. We did use a yaml file and the title of the PR threw me off. The issue is due to the extension being `.yaml` instead of `.yml`. This issue was raised to the developers of the monitor a while back as currently they only support `.yml`.

**Comment by thepetk** [comment]
> > @thepetk I was looking over the docs again and noticed there has to be a specific naming convention for the `security-insights` file to be picked up by the clomonitor scan. It has to be named `security-insights.yml`. From looking at the monitor it isn't tracking properly for alizer.
> > https://clomonitor.io/docs/topics/checks/#security-insights
> 
> never mind. We did use a yaml file and the title of the PR threw me off. The issue is due to the extension being `.yaml` instead of `.yml`. This issue was raised to the developers of the monitor a while back as currently they only support `.yml`.

@Jdubrick I've created a PR to rename the file here: https://github.com/devfile/alizer/pull/52

**Pull request merged**
